{
 "title": "MONITORAMENTO ZABBIX SERVER - EM DESENVOLVIMENTO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "grupo", "label": "GRUPO", "query": "*" },
   { "name": "host", "label": "SERVIDOR", "query": "$grupo.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<br>\n<h1 style=\"text-align: center;\"><img src=\"https://images.esp-online.com/thumbnails/aws_solution_list_thumbnail/2614/9455/9402/ZABBIX_LOGO.jpg\" alt=\"\" width=\"191\" height=\"50\" /></h1>\n<h1 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><strong>$host</strong></span></h1>",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "SISTEMA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AGENTE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Agent ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " LOGADOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of logged in users" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HISTÓRICO: CACHE LIVRE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Zabbix history write cache, % free"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CACHE DOS VALORES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix value cache hits" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROCESSOS EM EXECUÇÃO ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of running processes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "NOVAS CONSULTAS POR SEGUNDO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Values processed by Zabbix server per second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "TRIGGERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ALERTAS",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "PROCESSOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "QUANTIDADE TOTAL DE PROCESSOS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "targets": [
    {
     "application": { "filter": "Processes" },
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of processes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ICMP PING" ],
       "text": "setAlias(ICMP PING)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Zabbix busy icmp pinger processes, in %"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POLLERS" ],
       "text": "setAlias(POLLERS)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Zabbix busy poller processes, in %"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HISTÓRICO OCUPADO" ],
       "text": "setAlias(HISTÓRICO OCUPADO)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Zabbix busy history syncer processes, in %"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "HOUSEKEEPER" ],
       "text": "setAlias(HOUSEKEEPER)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Zabbix busy housekeeper processes, in %"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ALERTAS" ],
       "text": "setAlias(ALERTAS)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Zabbix busy alerter processes, in %"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU/MEMORIA/INTERFACES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU VISÃO GERAL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU softirq time(.*)/",
        "TEMPO DE PROCESSAMENTO DA CPU$1"
       ],
       "text": "replaceAlias(/CPU softirq time(.*)/, TEMPO DE PROCESSAMENTO DA CPU$1)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU iowait time(.*)/",
        "TEMPO DE IOWAIT DA CPU$1"
       ],
       "text": "replaceAlias(/CPU iowait time(.*)/, TEMPO DE IOWAIT DA CPU$1)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU user time(.*)/",
        "TEMPO DE USUÁRIO DA CPU$1"
       ],
       "text": "replaceAlias(/CPU user time(.*)/, TEMPO DE USUÁRIO DA CPU$1)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU idle time(.*)/",
        "$1 CPU TEMPO IDLE"
       ],
       "text": "replaceAlias(/CPU idle time(.*)/, $1 CPU TEMPO IDLE)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU system time(.*)/",
        "TEMPO DE SISTEMA DA CPU$1"
       ],
       "text": "replaceAlias(/CPU system time(.*)/, TEMPO DE SISTEMA DA CPU$1)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU nice time(.*)/",
        "TEMPO AGRADÁVEL DA CPU$1"
       ],
       "text": "replaceAlias(/CPU nice time(.*)/, TEMPO AGRADÁVEL DA CPU$1)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU steal time(.*)/",
        "TEMPO DE PERCA DA CPU$1"
       ],
       "text": "replaceAlias(/CPU steal time(.*)/, TEMPO DE PERCA DA CPU$1)",
       "added": false
      },
      {
       "def": {
        "name": "replaceAlias",
        "category": "Alias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ],
        "defaultParams": [
         "/(.*)/",
         "$1"
        ]
       },
       "params": [
        "/CPU interrupt time(.*)/",
        "TEMPO DE INTERRUPÇÃO DA CPU$1"
       ],
       "text": "replaceAlias(/CPU interrupt time(.*)/, TEMPO DE INTERRUPÇÃO DA CPU$1)",
       "added": false
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU.*time$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CARGA DO PROCESSADOR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [
        "Carga do processador (média de 1 min por núcleo)"
       ],
       "text": "setAlias(Carga do processador (média de 1 min por núcleo))"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [
        "Carga do processador (média de 5 min por núcleo)"
       ],
       "text": "setAlias(Carga do processador (média de 5 min por núcleo))"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Processor load (5 min average per core)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [
        "Carga do processador (média de 15 min por núcleo)"
       ],
       "text": "setAlias(Carga do processador (média de 15 min por núcleo))"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Processor load (15 min average per core)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "FILA DO SERVIDOR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "scale",
        "category": "Transform",
        "params": [
         {
          "name": "factor",
          "type": "float",
          "options": [
           100,
           0.01,
           10,
           -1
          ]
         }
        ],
        "defaultParams": [
         100
        ]
       },
       "params": [ "100" ],
       "text": "scale(100)"
      },
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "PROCESSOS EM FILA" ],
       "text": "setAlias(PROCESSOS EM FILA)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix preprocessing queue" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "FILA" ],
       "text": "setAlias(FILA)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Zabbix queue" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TRÁFEGO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "TRÁFEGO DE ENTRADA " ],
       "text": "setAlias(TRÁFEGO DE ENTRADA )"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Incoming network traffic on .*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "TRÁFEGO DE SAÍDA" ],
       "text": "setAlias(TRÁFEGO DE SAÍDA)"
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Outgoing network traffic on .*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MEMÓRIA DISPONÍVEL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "MEMÓRIA " ],
       "text": "setAlias(MEMÓRIA )",
       "added": false
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DISCO DISPONÍVEL ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "DISPONÍVEL ON/" ],
       "text": "setAlias(DISPONÍVEL ON/)",
       "added": false
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Free disk space on /" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "name": "setAlias",
        "category": "Alias",
        "params": [
         { "name": "alias", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "DISPONÍVEL ON /BOOT" ],
       "text": "setAlias(DISPONÍVEL ON /BOOT)",
       "added": false
      }
     ],
     "group": { "filter": "$grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "Free disk space on /boot" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}